apiVersion: apps/v2
kind: Deployment
metadata:
  name: playground-app
  namespace: dev
  labels:
    app: playground
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
        version: v2
    spec:
      containers:
      - name: playground
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
        env:
        - name: VERSION
          value: "v2"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 5
