apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-app
  namespace: dev
  labels:
    app: playground
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
        version: v2
    spec:
      containers:
      - name: playground
        image: wil42/playground:v2
        ports:
        - containerPort: 8888