apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

namespace: dev

commonLabels:
  managed-by: argocd
  environment: dev

images:
- name: wil42/playground
  newTag: v2
